#!/usr/bin/env python3
"""
report_generator.py
Generates standardized audit reports in Markdown format.
Ensures consistent output across all audit types.
"""

import os
import sys
import json
from datetime import datetime

# Configuration
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
AGENT_DIR = os.path.dirname(os.path.dirname(SCRIPT_DIR))
PROJECT_ROOT = os.path.dirname(AGENT_DIR)
REPORTS_DIR = os.path.join(PROJECT_ROOT, "docs", "reports")

# Report templates
TEMPLATES = {
    "security": """# 🔐 Security Audit Report

**Generated:** {timestamp}
**Scope:** {scope}

## Summary
- **Risk Level:** {risk_level}
- **Issues Found:** {issue_count}
- **Critical:** {critical_count}

## Findings

{findings_table}

## Recommendations

{recommendations}

---
*Generated by report_generator.py*
""",
    
    "database": """# 🗄️ Database Audit Report

**Generated:** {timestamp}
**Scope:** {scope}

## Summary
- **Tables Analyzed:** {table_count}
- **Issues Found:** {issue_count}
- **Performance Risks:** {perf_risks}

## Schema Analysis

{schema_analysis}

## Recommendations

{recommendations}

---
*Generated by report_generator.py*
""",
    
    "health": """# 🏥 System Health Report

**Generated:** {timestamp}

## Health Score: {score}/100

### Checks Passed
{passed_checks}

### Checks Failed
{failed_checks}

### Warnings
{warnings}

---
*Generated by report_generator.py*
""",
    
    "generic": """# 📋 Audit Report

**Generated:** {timestamp}
**Type:** {audit_type}

## Summary

{summary}

## Findings

{findings}

## Action Items

{action_items}

---
*Generated by report_generator.py*
"""
}

class ReportGenerator:
    def __init__(self):
        os.makedirs(REPORTS_DIR, exist_ok=True)
    
    def generate(self, audit_type, data):
        """Generate a report from audit data."""
        template = TEMPLATES.get(audit_type, TEMPLATES["generic"])
        
        # Add timestamp
        data["timestamp"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        
        # Generate findings table if needed
        if "findings" in data and isinstance(data["findings"], list):
            data["findings_table"] = self._generate_table(data["findings"])
        
        # Fill template
        try:
            report = template.format(**data)
        except KeyError as e:
            # Fill missing keys with placeholder
            data[str(e).strip("'")] = "_Not provided_"
            report = template.format(**data)
        
        return report
    
    def _generate_table(self, findings):
        """Generate Markdown table from findings list."""
        if not findings:
            return "_No findings_"
        
        # Get headers from first item
        headers = list(findings[0].keys())
        
        # Build table
        lines = []
        lines.append("| " + " | ".join(headers) + " |")
        lines.append("| " + " | ".join(["---"] * len(headers)) + " |")
        
        for item in findings:
            row = [str(item.get(h, "")) for h in headers]
            lines.append("| " + " | ".join(row) + " |")
        
        return "\n".join(lines)
    
    def save(self, report, filename):
        """Save report to file."""
        filepath = os.path.join(REPORTS_DIR, filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(report)
        return filepath
    
    def generate_and_save(self, audit_type, data, filename=None):
        """Generate and save a report."""
        report = self.generate(audit_type, data)
        
        if not filename:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            filename = f"{audit_type}_report_{timestamp}.md"
        
        filepath = self.save(report, filename)
        return filepath, report

def main():
    generator = ReportGenerator()
    
    if len(sys.argv) < 2:
        print("Usage: report_generator.py [generate <type> | list | demo]")
        print("\nTypes: security, database, health, generic")
        sys.exit(0)
    
    action = sys.argv[1]
    
    if action == "demo":
        # Generate demo report
        data = {
            "scope": "Full project scan",
            "risk_level": "🟡 Medium",
            "issue_count": 3,
            "critical_count": 1,
            "findings": [
                {"Severity": "🔴 Critical", "Issue": "Hardcoded API key", "File": "config.php"},
                {"Severity": "🟡 Medium", "Issue": "No rate limiting", "File": "api.php"},
                {"Severity": "🟢 Low", "Issue": "Debug mode enabled", "File": ".env"},
            ],
            "recommendations": "1. Remove hardcoded keys\n2. Implement rate limiting\n3. Disable debug in production"
        }
        
        filepath, report = generator.generate_and_save("security", data, "demo_report.md")
        print(f"✅ Demo report generated: {filepath}")
        print("\n" + "=" * 50)
        print(report[:500] + "...")
    
    elif action == "list":
        if os.path.exists(REPORTS_DIR):
            files = os.listdir(REPORTS_DIR)
            print(f"📋 Reports in {REPORTS_DIR}:")
            for f in files:
                print(f"   - {f}")
        else:
            print("No reports directory yet")
    
    elif action == "generate" and len(sys.argv) >= 3:
        audit_type = sys.argv[2]
        # Read data from stdin or file
        print(f"Generating {audit_type} report...")
        print("(Provide JSON data via stdin or use 'demo' command)")
    
    else:
        print("Unknown action")
        sys.exit(1)

if __name__ == "__main__":
    main()
